volumes:
  postgres_data:

services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: budgy
      POSTGRES_PASSWORD: budgy
      POSTGRES_DB: budgy
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: budgy@probi.home
      PGADMIN_DEFAULT_PASSWORD: budgy
    ports:
      - "8080:80"
    depends_on:
      - postgres